name: Terraform Multi-Environment CI/CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform environment to deploy'
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod
      action:
        description: 'Terraform Action to Perform'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
      confirm_destroy:
        description: 'Type YES to confirm destroy (required only if action is destroy)'
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event.inputs.action == 'plan'
    uses: ./.github/workflows/_terraform_template.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      action: plan
      confirm_destroy: ''
    secrets: inherit
  apply:
    if: github.event.inputs.action == 'apply'
    needs: plan #as we are using the plan artifact
    uses: ./.github/workflows/_terraform_template.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      action: apply
      confirm_destroy: ''
    secrets: inherit

  destroy:
    if: github.event.inputs.action == 'destroy' && github.event.inputs.confirm_destroy == 'YES'
    uses: ./.github/workflows/_terraform_template.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      action: destroy
      confirm_destroy: YES
    secrets: inherit
